.ALIASES
V_V1            V1(+=OUT -=0 ) CN @009_SIMULATIONPROFILE_EX6_3.SCHEMATIC1(sch_1):INS26@SOURCSTM.VSTIM.Normal(chips)
R_R1            R1(1=0 2=OUT ) CN @009_SIMULATIONPROFILE_EX6_3.SCHEMATIC1(sch_1):INS51@ANALOG.R.Normal(chips)
_    _(out=OUT)
.ENDALIASES
